name: 'Component Owners'
on:
  pull_request_target:

permissions:
  contents: read          # to read changed files
  issues: write           # to read/write issue assignees
  pull-requests: write    # to read/write PR reviewers

jobs:
  run_self:
    runs-on: ubuntu-latest
    name: Auto Assign Owners
    steps:
      - uses: dyladan/component-owners@7ff2b343629407c4dbe1c28ae66f55f723543d2b
        with:
          config-file: .github/component_owners.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
